FROM golang:alpine3.18
RUN apk add --no-cache \
        gcc \
        libc-dev \
        librdkafka-dev=2.1.1-r0 \
        pkgconf


RUN mkdir /app
COPY go.mod /app
WORKDIR /app

RUN go mod download
RUN go get -u github.com/nathany/looper
RUN go install github.com/nathany/looper
