version: '3'

services:
  main:
    depends_on:
      - system
    image: ${APP_NAME}_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CACHE_TTL: 1h
      CACHE_NUM_COUNTERS: 10000
      CACHE_MAX_COST: 10000
      CACHE_BUFFER_ITEMS: 64
      RELOADLY_SANDBOX: 'true'
      BOTSERVER_URL: ''
      CHATBASE_DATABASE: chatroach
      CHATBASE_HOST: cockroachdb
      CHATBASE_PORT: 26257
      CHATBASE_USER: root
      CHATBASE_MAX_CONNECTIONS: 1
      KAFKA_BROKERS: ''
      KAFKA_POLL_TIMEOUT: ''
      KAFKA_TOPIC: ''
      KAFKA_GROUP: ''
      DINERSCLUB_BATCH_SIZE: 1
      DINERSCLUB_RETRY_BOTSERVER: 1s
      DINERSCLUB_RETRY_PROVIDER: 1s
      DINERSCLUB_POOL_SIZE: 1
      DINERSCLUB_PROVIDERS: 'fake,reloadly'
      BACK_OFF_RANDOM_FACTOR: 0
    command: |
      sh -c '
        echo "Running tests..."
        go mod tidy

        if [ -z "${ARG}" ]
        then
          nodemon \
            --ext "*" \
            --exec "go test -cover -tags dynamic"
        fi

        if [ "${ARG}" = "--is-ci" ]
        then
          go test -cover -tags dynamic
          exit
        fi

        nodemon \
          --ext "*" \
          --exec "go test -cover -tags dynamic -run ${ARG}"
      '
    volumes:
      - ./:/app
    networks:
      - fly
  system:
    build:
      context: ../system
    environment:
      CHATBASE_DATABASE: chatroach
      CHATBASE_HOST: cockroachdb
      CHATBASE_PORT: 26257
      CHATBASE_USER: root
      PORT: 80
    command: go run .
    ports:
      - 80:80
    volumes:
      - ../system:/app
    networks:
      - fly
  initdb:
    image: cockroachdb/cockroach:v20.1.4
    depends_on:
      - cockroachdb
    entrypoint: |
      sh -c '
        /tools/wait-for-it.sh cockroachdb:26257 -t 60
        cat /migrations/* > /tmp/merged-latest.sql
        cat /tmp/merged-latest.sql | ./cockroach sql --insecure --host cockroachdb
      '
    volumes:
      - ../devops:/tools
      - ../devops/sql:/migrations
    networks:
      - fly
  cockroachdb:
    image: cockroachdb/cockroach:v20.1.4
    command: start --insecure
    ports:
      - 26257:26257
    networks:
      - fly

networks:
  fly:
    driver: bridge
