loki:
  enabled: true
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 50Gi


promtail:
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: kafka
          kafka:
            use_incoming_timestamp: true
            brokers:
            - kafka-headless.default.svc.cluster.local:29092
            group_id: loki
            topics:
            - vlab-prod-payment
            - vlab-prod-response
            - ^promtail.*
            labels:
              job: kafka
          relabel_configs:
              - action: replace
                source_labels:
                  - __meta_kafka_topic
                target_label: topic
              - action: replace
                source_labels:
                  - __meta_kafka_partition
                target_label: partition
              - action: replace
                source_labels:
                  - __meta_kafka_group_id
                target_label: group
