version: '3'

services:
  main:
    depends_on:
      - cockroachdb
    build: .
    image: formcentral
    environment:
      CHATBASE_DATABASE: chatroach
      CHATBASE_HOST: cockroachdb
      CHATBASE_PORT: 26257
      CHATBASE_USER: root
    command: |
      bash -c '
        go get -u github.com/nathany/looper
        tools/wait-for-it.sh cockroachdb:26257 -t 60
        go test || true
        looper
      '
    volumes:
      - ./:/app
      - ../tools:/app/tools    
  cockroachdb:
    image: cockroachdb/cockroach:v20.1.4
    command: start --insecure
    ports:
      - 26257:26257
