version: '3'

services:
  main:
    depends_on:
      - postgres
    build: .
    image: formcentral
    environment:
      POSTGRES_DB: test-db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    command: |
      bash -c '
        go get -u github.com/nathany/looper
        tools/wait-for-it.sh postgres:5432 -t 60 &&
        go test &&
        looper
      '
    volumes:
      - ./:/app
      - ../tools:/app/tools
  postgres:
    image: postgres:9.6.11-alpine
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-pass
    ports:
      - 5432:5432
