apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zk
spec:
  replicas: 3
  image:
    repository: pravega/zookeeper
    tag: "0.2.15"
    pullPolicy: IfNotPresent
  pod:
    resources:
      requests:
        cpu: 15m
        memory: 100Mi
