---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
# We should have a kind cluster that has some workers
# to speed up deployment
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
- role: worker
