---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Use a stable Kubernetes version instead of experimental v1.34.0
# Available images: https://github.com/kubernetes-sigs/kind/releases
# kindest/node:v1.29.2 is a stable release
name: kind
containerdConfigPatches:
# required for the local registry
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  extraPortMappings:
  # Exposes ingress controller on 0.0.0.0:80
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  # Exposes ingress controller on 0.0.0.0:443 (TLS)
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  # Exposes kafka on 0.0.0.0:30092
  - containerPort: 30092
    hostPort: 30092
    protocol: TCP
  # Exposes cockroachdb on 0.0.0.0:35432
  - containerPort: 32432
    hostPort: 32432
    protocol: TCP
- role: worker
- role: worker
