tags:
  kafka: false
  cockroach: true
  backup: false

kafkabrokers: &kb "kafka-headless.default.svc.cluster.local:29092"
chatTopic: &topic "vlab-test-chat-events"
botEnvs: &botenvs gbv-bot-envs
chatbaseHost: &host "gbv-cockroachdb-public"

versionDashboard: &vdashboard 0.0.4
versionNaughtybot: &vnaughtybot 0.0.12
versionBotserver: &vbotserver 0.0.6
versionReplybot: &vreplybot 0.0.64
versionBotscribe: &vbotscribe 0.0.6

consumerAlerts: []
laggingAlerts: []

kafkaTopics:
  - name: *topic
    partitions: 1
    replicationFactor: 1
    config:
      "retention.ms": "86400000" # 1 day


replybot:
  replicaCount: 1
  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: *topic
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: DASHBOARD_API
    value: "http://gbv-dashboard/api/v1"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  - name: FORMCENTRAL_URL
    value: "http://gbv-formcentral"

naughtybot:
  image:
    repository: vlabresearch/naughtybot
    tag: *vnaughtybot
    pullPolicy: IfNotPresent

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"

  writer:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 64Mi

  dean:
    schedule: "*/1 * * * *"
    resources:
      requests:
        cpu: 10m
        memory: 64Mi


linksniffer:
  replicaCount: 1

  image:
    repository: vlabresearch/linksniffer
    tag: 0.0.3
    pullPolicy: IfNotPresent

  env:
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"
  - name: FB_PAGE_ID
    value: "935593143497601"

  resources:
    requests:
      cpu: 10m
      memory: 50Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbvlinks-staging.nandan.cloud
        paths:
          - "/"
    tls:
      - secretName: gbv-linksniffer-cert
        hosts:
          - gbvlinks-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80

dashboard:
  replicaCount: 1

  image:
    repository: vlabresearch/dashboard
    tag: *vdashboard
    pullPolicy: IfNotPresent

  envFrom: *botenvs
  env:
    - name: TYPEFORM_URL
      value: 'https://api.typeform.com'
    - name: CUBEJS_API_SECRET
      value: 'notasecret'
    - name: CUBEJS_DB_TYPE
      value: 'postgres'
    - name: DB_DATABASE
      value: 'chatroach'
    - name: CUBEJS_DB_NAME
      value: 'chatroach'
    - name: DB_USER
      value: 'chatroach'
    - name: CUBEJS_DB_USER
      value: 'chatroach'
    - name: DB_PASSWORD
      value: ''
    - name: CUBEJS_DB_PASS
      value: ''
    - name: DB_HOST
      value: *host
    - name: CUBEJS_DB_HOST
      value: *host
    - name: DB_PORT
      value: '26257'
    - name: CUBEJS_DB_PORT
      value: '26257'
    - name: TYPEFORM_REDIRECT_URL
      value: 'https://staging--vlab-research.netlify.com/surveys/auth'
    - name: FACEBOOK_GRAPH_URL
      value: 'https://graph.facebook.com/v7.0'

  resources:
    requests:
      cpu: 10m
      memory: 64Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbv-dashboard-staging.nandan.cloud
        paths:
          - '/'
    tls:
      - secretName: gbv-dashboard-cert
        hosts:
          - gbv-dashboard-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80



scratchbot:
  replicaCount: 1

  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent

  envFrom: *botenvs

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_nnEVENT_TOPIC
    value: *topic
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: DASHBOARD_API
    value: "http://gbv-dashboard/api/v1"

  resources:
    requests:
      cpu: 10m
      memory: 64Mi



botscribe:
  replicaCount: 1

  image:
    repository: vlabresearch/botscribe
    tag: *vbotscribe
    pullPolicy: IfNotPresent

  envFrom: *botenvs

  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSCRIBE_HIGHWATER
    value: "500"
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic

  resources:
    requests:
      cpu: 10m
      memory: 64Mi


botserver:
  replicaCount: 1

  image:
    repository: vlabresearch/botserver
    tag: *vbotserver
    pullPolicy: IfNotPresent

  envFrom: *botenvs

  env:
  - name: BOTSERVER_EVENT_TOPIC
    value: *topic
  - name: KAFKA_BROKERS
    value: *kb

  resources:
    requests:
      cpu: 10m
      memory: 128Mi

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: gbvbot-staging.nandan.cloud
        paths:
          - "/"
    tls:
      - secretName: gbv-botserver-cert
        hosts:
          - gbvbot-staging.nandan.cloud

  service:
    type: ClusterIP
    port: 80


cockroachdb:
  statefulset:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 500Mi
  conf:
    cache: 250MiB
    max-sql-memory: 250MiB
    max-disk-temp-storage: 4GiB
    budget:
      maxUnavailable: 0
  tls:
    enabled: no
  storage:
    persistentVolume:
      size: 5Gi
      storageClass: "pd-ssd"
