tags:
  kafka: true
  cockroach: true
  payments: true
  backup: false
  naughtybot: false
  botscribe: false
  scratchbot: false

processingAlerts: []
laggingAlerts: []
kafkaTopics: []

chatTopic: &topic chat-events
stateTopic: &statetopic vlab-state
responseTopic: &responsetopic vlab-response
paymentTopic: &paymenttopic vlab-payment
kafkabrokers: &kb gbv-kafka:9092
botEnvs: &botenvs gbv-bot-envs
chatbaseHost: &host gbv-cockroachdb-public

versionDashboard: &vdashboard 0.0.26
versionBotserver: &vbotserver 0.0.9
versionReplybot: &vreplybot v0.0.126
versionLinksniffer: &vlinksniffer v0.0.4
versionDean: &vdean v0.0.24
versionScribble: &vscribble 0.0.20
versionDinersclub: &vdinersclub v0.0.11
versionFormcentral: &vformcentral v0.0.7

linksniffer:
  replicaCount: 1
  image:
    repository: vlabresearch/linksniffer
    tag: *vlinksniffer
    pullPolicy: IfNotPresent
  env:
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi
  ingress:
    enabled: false
  service:
    type: ClusterIP
    port: 80

formcentral:
  replicaCount: 1
  image:
    tag: *vformcentral
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  resources:
    requests:
      cpu: 10m
      memory: 10Mi

dinersclub:
  image:
    repository: vlabresearch/dinersclub
    tag: *vdinersclub
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
  envFrom: gbv-bot-envs
  env:
    - name: CACHE_TTL
      value: "1h"
    - name: CACHE_NUM_COUNTERS
      value: "1000"
    - name: CACHE_MAX_COST
      value: "1000"
    - name: CACHE_BUFFER_ITEMS
      value: "64"
    - name: RELOADLY_SANDBOX
      value: "true"
    - name: BOTSERVER_URL
      value: "http://gbv-botserver/synthetic"
    - name: CHATBASE_DATABASE
      value: "chatroach"
    - name: CHATBASE_HOST
      value: *host
    - name: CHATBASE_PORT
      value: "26257"
    - name: CHATBASE_USER
      value: "chatroach"
    - name: CHATBASE_MAX_CONNECTIONS
      value: "1"
    - name: KAFKA_BROKERS
      value: *kb
    - name: KAFKA_POLL_TIMEOUT
      value: "1s"
    - name: KAFKA_TOPIC
      value: *paymenttopic
    - name: KAFKA_GROUP
      value: "dinersclub"
    - name: DINERSCLUB_BATCH_SIZE
      value: "1"
    - name: DINERSCLUB_RETRY_BOTSERVER
      value: "2m"
    - name: DINERSCLUB_RETRY_PROVIDER
      value: "2m"
    - name: DINERSCLUB_POOL_SIZE
      value: "1"
    - name: DINERSCLUB_PROVIDERS
      value: "fake,reloadly"

dashboard:
  replicaCount: 1
  image:
    repository: vlabresearch/dashboard
    tag: *vdashboard
    pullPolicy: IfNotPresent
  envFrom: *botenvs
  env:
    - name: TYPEFORM_URL
      value: 'https://api.typeform.com'
    - name: CUBEJS_API_SECRET
      value: 'notasecret'
    - name: CUBEJS_DB_TYPE
      value: 'postgres'
    - name: DB_DATABASE
      value: 'chatroach'
    - name: CUBEJS_DB_NAME
      value: 'chatroach'
    - name: DB_USER
      value: 'chatroach'
    - name: CUBEJS_DB_USER
      value: 'chatroach'
    - name: DB_PASSWORD
      value: ''
    - name: CUBEJS_DB_PASS
      value: ''
    - name: DB_HOST
      value: *host
    - name: CUBEJS_DB_HOST
      value: *host
    - name: DB_PORT
      value: '26257'
    - name: CUBEJS_DB_PORT
      value: '26257'
    - name: TYPEFORM_REDIRECT_URL
      value: 'https://localhost:3000/surveys/auth'
    - name: FORMCENTRAL_URL
      value: 'http://gbv-formcentral'
    - name: FACEBOOK_GRAPH_URL
      value: 'https://graph.facebook.com/v7.0'
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  ingress:
    enabled: false
  service:
    type: ClusterIP
    port: 80



replybot:
  replicaCount: 1
  image:
    repository: vlabresearch/replybot
    tag: *vreplybot
    pullPolicy: IfNotPresent
  envFrom: *botenvs
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  env:
  - name: CHATBASE_BACKEND
    value: "@vlab-research/chatbase-postgres"
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: FALLBACK_FORM
    value: "305"
  - name: REPLYBOT_EVENT_TOPIC
    value: *topic
  - name: FACEBOOK_GRAPH_URL
    value: "http://gbv-facebot"
  - name: BOTSPINE_KAFKA_BROKERS
    value: *kb
  - name: KAFKA_BROKERS
    value: *kb
  - name: BOTSPINE_MESSAGE_TOPIC
    value: *topic
  - name: VLAB_STATE_TOPIC
    value: *statetopic
  - name: VLAB_RESPONSE_TOPIC
    value: *responsetopic
  - name: VLAB_PAYMENT_TOPIC
    value: *paymenttopic
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
  - name: FORMCENTRAL_URL
    value: "http://gbv-formcentral"

botserver:
  replicaCount: 1
  image:
    repository: vlabresearch/botserver
    tag: *vbotserver
    pullPolicy: IfNotPresent
  envFrom: *botenvs
  env:
  - name: BOTSERVER_EVENT_TOPIC
    value: *topic
  - name: KAFKA_BROKERS
    value: *kb
  - name: PORT
    value: "80"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
  ingress:
    enabled: false
  service:
    type: ClusterIP
    port: 80

dean:
  image:
    repository: vlabresearch/dean
    tag: *vdean
    pullPolicy: IfNotPresent
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver/synthetic"
  - name: DEAN_FB_CODES
    value: "2022,-1"
  - name: DEAN_ERROR_TAGS
    value: "NETWORK,INTERNAL"
  - name: DEAN_ERROR_INTERVAL
    value: "24 hours"
  - name: DEAN_BLOCKED_INTERVAL
    value: "24 hours"
  - name: DEAN_RESPONDING_INTERVAL
    value: "23 hours"
  - name: DEAN_RESPONDING_GRACE
    value: "1 hour"
  - name: DEAN_SEND_DELAY
    value: "1ms"
  - name: DEAN_FOLLOWUP_MIN
    value: "1 minute"
  - name: DEAN_FOLLOWUP_MAX
    value: "1 hour"
  queries:
    - name: respondings
      queries: "respondings,blocked,errored"
      schedule: "*/1 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi
    - name: timeouts
      queries: "timeouts,followups"
      schedule: "*/1 * * * *"
      resources:
        requests:
          cpu: 10m
          memory: 10Mi

scribble:
  image:
    repository: vlabresearch/scribble
    tag: *vscribble
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 32Mi
  env:
  - name: CHATBASE_DATABASE
    value: "chatroach"
  - name: CHATBASE_USER
    value: "chatroach"
  - name: CHATBASE_PASSWORD
    value: ""
  - name: CHATBASE_HOST
    value: *host
  - name: CHATBASE_PORT
    value: "26257"
  - name: KAFKA_BROKERS
    value: *kb
  - name: KAFKA_POLL_TIMEOUT
    value: "1s"
  - name: SCRIBBLE_CHUNK_SIZE
    value: "32"
  - name: SCRIBBLE_BATCH_SIZE
    value: "32"
  - name: SCRIBBLE_ERROR_HANDLERS
    value: ""

  sinks:
    - destination: "states"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *statetopic
      - name: KAFKA_GROUP
        value: "scribble-states"

    - destination: "responses"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *responsetopic
      - name: KAFKA_GROUP
        value: "scribble-responses"

    - destination: "messages"
      replicaCount: 1
      env:
      - name: KAFKA_TOPIC
        value: *topic
      - name: KAFKA_GROUP
        value: "scribble-messages"


cockroachdb:
  image:
    tag: v20.1.4
  statefulset:
    replicas: 1
  conf:
    budget:
      maxUnavailable: 0
  tls:
    enabled: no
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
  storage:
    persistentVolume:
      size: 1Gi

kafka:
  resources:
    requests:
      cpu: 25m
      memory: 200Mi
  zookeeper:
    resources:
      requests:
        cpu: 5m
        memory: 50Mi
  heapOpts: "-Xmx500M -Xms500M"
  autoCreateTopicsEnable: false
  defaultReplicationFactor: 1
  offsetsTopicReplicationFactor: 1
  persistence:
    size: 1Gi
  provisioning:
    enabled: true
    topics:
      - name: *topic
        partitions: 6
        replicationFactor: 1
        config:
          # 14 days
          retention.ms: "1209600000"
      - name: *statetopic
        partitions: 6
        replicationFactor: 1
        config:
          retention.ms: "1209600000"
      - name: *responsetopic
        partitions: 6
        replicationFactor: 1
        config:
          retention.ms: "1209600000"
      - name: *paymenttopic
        partitions: 2
        replicationFactor: 1
        config:
          retention.ms: "1209600000"
