version: 2

jobs:
  test_dashboard_server:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh dashboard-server --is-ci
  test_dean:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh dean --is-ci
  test_dinersclub:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh dinersclub --is-ci
  test_formcentral:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh formcentral --is-ci
  test_linksniffer:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh linksniffer --is-ci
  test_replybot:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh replybot --is-ci
  test_scribble:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          command: ./test.sh scribble --is-ci
  test_e2e:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - run:
          name: Install Kubectl/Helm
          command: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              sudo mv ./kubectl /usr/local/bin/kubectl
              curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
              kubectl version --client
              helm version
      - run:
          name: Install kind
          command: |
              GO111MODULE="on" go get sigs.k8s.io/kind@v0.8.1
      - run:
          name: Setup kind cluster
          command: |
              kind create cluster --name test --wait 5m
              kubectl config use-context kind-test
      - run:
          name: Run tests
          command: cd devops && ./integration-test.sh

workflows:
  version: 2
  test:
    jobs:
      - test_dashboard_server
      - test_dean
      - test_dinersclub
      - test_formcentral
      - test_linksniffer
      - test_replybot
      - test_scribble
      - test_e2e:
          context: secrets
