version: 2

jobs:
  test_dinersclub:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          command: ./test.sh dinersclub --is-ci
  test_formcentral:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          command: ./test.sh formcentral --is-ci
  test_e2e:
    machine:
      image: ubuntu-2204:2022.04.1
    steps:
      - checkout
      - run:
          name: Install Kubectl/Helm
          command: |
              curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
              chmod +x ./kubectl
              sudo mv ./kubectl /usr/local/bin/kubectl
              curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
              kubectl version --client
              helm version
      - run:
          name: Install kind
          command: |
              GO111MODULE="on" go install sigs.k8s.io/kind@v0.14.0
      - run:
          name: Setup kind cluster
          command: |
              kind create cluster --name test --wait 5m
              kubectl config use-context kind-test
      - run:
          name: Run tests
          command: cd devops && make integration-tests

workflows:
  version: 2
  test:
    jobs:
      - test_dinersclub
      - test_formcentral
      - test_e2e:
          context: secrets
