replicaCount: 2
image:
  repository: ghcr.io/vlab-research/message-worker
  tag: 0.1.0
  pullPolicy: IfNotPresent
envFrom: "gbv-bot-envs"
env:
  - name: KAFKA_BROKERS
    value: "kafka-headless.default.svc.cluster.local:29092"
  - name: LOG_LEVEL
    value: "info"
  - name: HEALTH_PORT
    value: "8081"
  - name: BOTSERVER_URL
    value: "http://gbv-botserver"
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
