FROM golang:alpine

RUN apk add --no-cache \
    gcc \
    libc-dev \
    librdkafka-dev=1.8.2-r0 \
    npm \
    readline-dev

RUN mkdir /app
COPY go.mod /app
WORKDIR /app

RUN go mod download
RUN npm install -g nodemon
