version: '3'

services:
  main:
    image: cockroachdb/cockroach:v20.1.4
    depends_on:
      - cockroachdb
    entrypoint: |
      sh -c '
        /tools/wait-for-it.sh cockroachdb:26257 -t 60
        cat /migrations/* > /tmp/merged-latest.sql
        cat /tmp/merged-latest.sql | ./cockroach sql --insecure --host cockroachdb
        ./cockroach dump chatroach --insecure --host cockroachdb --dump-mode=schema
      '
    volumes:
      - ../devops:/tools
      - ../devops/sql:/migrations
    networks:
      - fly
  cockroachdb:
    image: cockroachdb/cockroach:v20.1.4
    command: start --insecure
    ports:
      - 26257:26257
    networks:
      - fly

networks:
  fly:
    driver: bridge
