image:
  tag: v24.1.28
statefulset:
  replicas: 1
  args:
    - --insecure
  budget:
    maxUnavailable: 0
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
conf:
  single-node: true
ingress:
  enabled: true
  hosts:
  - cockroachdb.fly.local
tls:
  enabled: false
storage:
  persistentVolume:
    size: 5Gi
