image:
  tag: v21.2.17
statefulset:
  replicas: 1
  args:
    - --insecure 
conf:
  single-node: true
  budget:
    maxUnavailable: 0
ingress:
  enabled: true
  hosts:
  - cockroachdb.fly.local
tls:
  enabled: false
resources:
  requests:
    cpu: 25m
    memory: 256Mi
storage:
  persistentVolume:
    size: 1Gi
