apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebot
  labels:
    app: facebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebot
  template:
    metadata:
      labels:
        app: facebot
    spec:
      containers:
      - name: facebot
        image: vlabresearch/facebot:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "30Mi"
        ports:
        - containerPort: 3000
        - containerPort: 4000
        envFrom:
        - secretRef:
            name: bot-envs
---

kind: Service
apiVersion: v1
metadata:
  # TODO this is hard coded in a couple of places
  # we should update it
  name: gbv-facebot
spec:
  selector:
    app: facebot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
