apiVersion: batch/v1
kind: Job
metadata:
  name: testrunner
  labels:
    app: testrunner
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: testrunner
    spec:
      restartPolicy: OnFailure
      containers:
      - name: testrunner
        image: vlabresearch/testrunner:v0.0.7
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "30Mi"
        ports:
        - containerPort: 88
        envFrom:
        - secretRef:
            name: bot-envs
        env:
        - name: BOTSERVER_URL
          value: "http://fly-botserver"
        - name: KAFKA_BROKERS
          value: "kafka:9092"
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "db-cockroachdb-public"
        - name: CHATBASE_PORT
          value: "26257"
