name: Dinersrclub
on:
  push: 
    # We should always build and test on main
    # in order to validate that no changes outside of the
    # dinersclub/ folder affect the build
    branches:
    - main
    tags:
    - 'dinersclub-*'
  pull_request:
    paths:
     - "dinersclub/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Run Tests
      run: make test IS_CI=true
      working-directory: dinersclub/
  build:
    runs-on: ubuntu-latest
    name: Build Image
    needs:
    - tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
# TODO: setup credentials for docker hub
#      - name: Login to registry
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set docker tags
        id: meta
        uses: docker/metadata-action@v4.1.1
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: vlabresearch/dinersclub
          tags: |
            type=sha,format=long,prefix=,priority=200
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/dinersclub') }},priority=100
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: dinersclub/
          # We only push to docker on tag with `dinersclub-x.x.x`
          push: ${{ startsWith(github.ref, 'refs/tags/dinersclub') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta.outputs.tags }}
