name: E2E
on:
  push: 
    # We should always build and test on main
    # in order to validate that no changes outside of the
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
     - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Install Dependencies
      # Note Github workers have kubectl installed on them already
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm version
    - name: Install Kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: true
    - name: Create Cluster
      run: make create-kind-cluster
      working-directory: devops
    - name: Run Tests
      run: make integration-tests
      working-directory: devops
